# Generated by Django 6.0.6 on 2026-07-02 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='video_file',
            field=models.FileField(default='', upload_to='videos/'),
            preserve_default=False,
        ),
    ]
